### ISSUE TITLE
Problems with inter clock timing

### ISSUE THREAD

**Issue by cklarhorst** [enjoy-digital/litepcie#113]
Hi all,

I'm trying to get litepcie to work on a custom board with a kintex.
While looking at the vivado output, I noticed many inter clock paths failing.
I also tried the sqrl_acorn board and it also has the same failing paths:

Example vivado timing log from sqrl_acorn with pcie enabled:
```
------------------------------------------------------------------------------------------------
| Inter Clock Table
| -----------------
------------------------------------------------------------------------------------------------

From Clock         To Clock               WNS(ns)      TNS(ns)  TNS Failing Endpoints  TNS Total Endpoints      WHS(ns)      THS(ns)  THS Failing Endpoints  THS Total Endpoints
----------         --------               -------      -------  ---------------------  -------------------      -------      -------  ---------------------  -------------------
s7pciephy_clkout0  sys_clk                 -5.005      -42.734                      9                    9        1.892        0.000                      0                    9
s7pciephy_clkout1  sys_clk                 -4.998      -42.669                      9                    9        1.899        0.000                      0                    9
s7pciephy_clkout3  sys_clk                 -6.265    -1978.372                    366                  366        1.767        0.000                      0                  366
s7pciephy_clkout1  s7pciephy_clkout0        0.029        0.000                      0                 2489        0.053        0.000                      0                 2489
s7pciephy_clkout0  s7pciephy_clkout1       -0.359       -0.359                      1                 2488        0.053        0.000                      0                 2488
sys_clk            s7pciephy_clkout3       -3.638      -23.324                     13                   13        0.611        0.000                      0                   13
```

I discovered that https://github.com/enjoy-digital/litex/blob/0c326f0ed009ce6cf8b000bb4b6c67ff595a766e/litex/soc/integration/soc.py#L2024 sets everything between sys_clk and pcie to a false path.
But I'm not sure what the pcie clock domain is and if that is maybe the source of my problem.
In https://github.com/enjoy-digital/litepcie/blob/a20bf8827793bf2aca69f131b4da2f6f212c4f43/litepcie/phy/s7pciephy.py#L230 pcie clock domain is only about the axi output clk. 
Does anybody know how that is supposed to work, should all paths between the clocks in litepci and sys_clk be set to false paths?
In my opinion, the false path should be set between the pcie ref input clock (for sqrl_acorn that would be pcie_x4_clk_p) and sys_clock  so that all clocks generated inside litepcie are also considered false paths instead of now where the false path is between "pcie" (The axi output clk inside litepcie) and "sys_clk".

The current version doesn't even set the false path. Vivado prints:
`CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks -include_generated_clocks -of [get_nets pcie_clk]]'`

Relevant lines from the generated XDC file:
```
create_clock -name pcie_x4_clk_p -period 10.0 [get_ports pcie_x4_clk_p]
set_clock_groups -group [get_clocks -include_generated_clocks -of [get_nets sys_clk]] -group [get_clocks -include_generated_clocks -of [get_nets pcie_clk]] -asynchronous
```

Maybe I'm totally on this. 
Thanks in advance for any hints on this.

**Comment by tzechienchu** [comment]
Dear Sir
I got the similar issue. I use Vivado 2018 and Vivado 2023.2 .
Both got the similar Critial Warring.
The sample code is copy from [sqrl_acorn.py] (https://github.com/enjoy-digital/acorn_pcie_compute_test/blob/master/sqrl_acorn.py)
--------------------------------------------------------------------------------------------------------------------------------------------------------
Last few message:

```
INFO: [Timing 38-35] Done setting XDC timing constraints.
WARNING: [Vivado 12-627] No clocks matched 'userclk2'.
INFO: [Vivado 12-626] No clocks found. Please use 'create_clock' or 'create_generated_clock' command to create clocks.
ERROR: [Vivado 12-5201] set_clock_groups: cannot set the clock group when only one non-empty group remains.
# set_clock_groups -group [get_clocks sys_clk] -group [get_clocks userclk2] -asynchronous
CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks userclk2]'.
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.
CRITICAL WARNING: [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group '.
Resolution: Check if the specified object(s) exists in the current design. If it does, ensure that the correct design hierarchy was specified for the object. If you are working with clocks, make sure create_clock was used to create the clock object before it is referenced.
INFO: [Common 17-206] Exiting Vivado at Fri Jan 19 11:03:45 2024...
Traceback (most recent call last):
  File "base.py", line 212, in <module>
    main()
  File "base.py", line 198, in main
    builder.build()
  File "/home/vivado23chu/Litex/litex/litex/soc/integration/builder.py", line 370, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/home/vivado23chu/Litex/litex/litex/soc/integration/soc.py", line 1383, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/vivado23chu/Litex/litex/litex/build/xilinx/platform.py", line 98, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/vivado23chu/Litex/litex/litex/build/xilinx/vivado.py", line 141, in build
    return GenericToolchain.build(self, platform, fragment, **kwargs)
  File "/home/vivado23chu/Litex/litex/litex/build/generic_toolchain.py", line 123, in build
    self.run_script(script)
  File "/home/vivado23chu/Litex/litex/litex/build/xilinx/vivado.py", line 401, in run_script
    raise OSError("Error occured during Vivado's script execution.")
OSError: Error occured during Vivado's script execution.
```
---------------------------------------------------------------------------------------------------------------------------------------------
I comment out 4 (platform.toolchain.pre_placement_commands.add ...)
as following. 

```
            self.add_pcie(phy=self.pcie_phy, ndmas=1, address_width=64)
            # FIXME: Apply it to all targets (integrate it in LitePCIe?).
            platform.add_period_constraint(self.crg.cd_sys.clk, 1e9/sys_clk_freq)
            #platform.toolchain.pre_placement_commands.add("set_clock_groups -group [get_clocks {sys_clk}] -group [get_clocks userclk2] -asynchronous", sys_clk=self.crg.cd_sys.clk)
            #platform.toolchain.pre_placement_commands.add("set_clock_groups -group [get_clocks {sys_clk}] -group [get_clocks clk_125mhz] -asynchronous", sys_clk=self.crg.cd_sys.clk)
            #platform.toolchain.pre_placement_commands.add("set_clock_groups -group [get_clocks {sys_clk}] -group [get_clocks clk_250mhz] -asynchronous", sys_clk=self.crg.cd_sys.clk)
            #platform.toolchain.pre_placement_commands.add("set_clock_groups -group [get_clocks clk_125mhz] -group [get_clocks clk_250mhz] -asynchronous")
```

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
It run and generate bit stream. But never test since I have not got my test board, yet.

Regards,
