### ISSUE TITLE
Interrupt vector conflict for IRQ 0

### ISSUE THREAD

**Issue by dh73** [enjoy-digital/litepcie#3]
Hi, 
I tried to run litepcie following the Readme step by step, on a Fedora 25 machine. 
After recursively clone litex (and litedram), the make.py shows this error:

`./make.py all
Traceback (most recent call last):
  File "./make.py", line 92, in <module>
    soc = top_class(platform, **top_kwargs)
  File "/home/dh/Documents/litepcie/example_designs/targets/dma.py", line 61, in __init__
    with_timer=False
  File "/usr/lib/python3.5/site-packages/litex-0.1-py3.5.egg/litex/soc/integration/soc_core.py", line 169, in __init__
    interrupt, mod_name, interrupt_rmap[interrupt]))
AssertionError: Interrupt vector conflict for IRQ 0, user defined nmi conflicts with SoC inbuilt dma_writer
`

I'm using default values of litepcie/example_design/targets ... is really the soc_core having conflicts with DMA example?

**Comment by enjoy-digital** [comment]
Hi,
thanks for reporting. We did some changes in LiteX recently and example design  was not up to date. I just fixed that.
